USE Usuarios;

CREATE TABLE Roles (
IdRol INT IDENTITY(1,1) PRIMARY KEY,
NombreRol VARCHAR(50) NOT NULL
);

CREATE TABLE Usuarios (
	IdUsuario INT IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Correo VARCHAR(50) NOT NULL UNIQUE,
	Contraseña VARCHAR(50) NOT NULL,
	IdRol INT NOT NULL,
	Estado BIT NOT NULL,
	FOREIGN KEY (IdRol) REFERENCES Roles(IdRol)
);